spring:
  application:
    name: feedback

  r2dbc:
    url: ${R2DBC_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: true
    url: ${JDBC_URL}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  main:
    web-application-type: reactive


logging:
  level:
    root: ${LOG_ROOT_LEVEL:INFO} # Passez le root en INFO par défaut pour le développement
    com.yowyob.feedback: ${LOG_APP_LEVEL:DEBUG} # Ciblez votre vrai package
    org.springframework.web: INFO # Pour voir ce que Spring WebFlux fait de nos réponses


springdoc:
  api-docs:
    path: ${SPRINGDOC_API_DOCS:/v3/api-docs}
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI:/swagger-ui.html}
    operations-sorter: alpha
    display-request-duration: true

  # Configuration Jackson pour les dates
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    default-property-inclusion: non_null

